export const sampleTours = [
  {
    title: "Sajek Valley: Cloud Kingdom Adventure",
    titleBn: "সাজেক ভ্যালি: মেঘের রাজ্যে অ্যাডভেঞ্চার",
    price: 6500,
    duration: "3 Days, 2 Nights",
    durationBn: "৩ দিন, ২ রাত",
    description: "Experience the magical floating clouds, traditional indigenous cuisine, and scenic green mountains of Sajek Valley, Rangamati.",
    descriptionBn: "রাঙ্গামাটির সাজেক ভ্যালিতে যাদুকারী ভাসমান মেঘ, ঐতিহ্যবাহী আদিবাসী খাবার এবং সবুজ পাহাড়ের মনোরম দৃশ্য উপভোগ করুন।",
    location: "Sajek Valley, Rangamati",
    locationBn: "সাজেক ভ্যালি, রাঙ্গামাটি",
    distanceNote: "340 km from Dhaka",
    imgUrl: "/images/sajek.png",
    popular: true,
    startDate: "2026-06-15",
    endDate: "2026-06-18",
    rating: "9.6",
    reviews: "142",
    inclusions: [
      "2 Nights accommodation in a premium Eco-Resort",
      "All traditional local meals (Breakfast, Lunch, Dinner)",
      "Chander Gari (4x4 Jeep) for local sightseeing",
      "Experienced local tour guide support",
      "All entry tickets and community fees"
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival and Sunset at Konglak Hill",
        titleBn: "আগমন ও কংলাক পাহাড়ে সূর্যাস্ত",
        description: "Arrive at Sajek, check into the resort. In the late afternoon, hike up to Konglak Hill, the highest point in Sajek, to experience a majestic sunset above the clouds.",
        descriptionBn: "সাজেকে পৌঁছানো ও রিসোর্টে চেক-ইন। শেষ বিকেলে কংলাক পাহাড়ে আরোহণ ও মেঘের ওপরে অপরূপ সূর্যাস্ত উপভোগ।"
      },
      {
        day: 2,
        title: "Sunrise at Helipad & Tour to Alutila Cave",
        titleBn: "হেলিপ্যাডে সূর্যোদয় এবং আলুটিলা গুহা ভ্রমণ",
        description: "Wake up early to catch the breathtaking sunrise from the helipad. After breakfast, head to Khagrachari to explore the Alutila Mysterious Cave and Risang Waterfall.",
        descriptionBn: "হেলিপ্যাড থেকে মনোরম সূর্যোদয় দেখতে ভোরে ঘুম থেকে ওঠা। সকালের নাস্তার পর খাগড়াছড়ির আলুটিলা রহস্যময় গুহা এবং রিসাং ঝর্ণা ভ্রমণ।"
      },
      {
        day: 3,
        title: "Morning Clouds and Return to Dhaka",
        titleBn: "সকালের মেঘ এবং ঢাকায় প্রত্যাবর্তন",
        description: "Enjoy your morning coffee surrounded by floating white clouds. Check out from the resort and start your return journey back to Dhaka with unforgettable memories.",
        descriptionBn: "ভেসে যাওয়া সাদা মেঘের মাঝে সকালের কফি উপভোগ করুন। রিসোর্ট থেকে বিদায় নিয়ে মনোরম সব স্মৃতি নিয়ে ঢাকার উদ্দেশ্যে ফিরতি যাত্রা শুরু।"
      }
    ],
    reviewsBreakdown: {
      "Location": 9.8,
      "Cleanliness": 9.5,
      "Service": 9.7,
      "Value for Money": 9.4
    }
  },
  {
    title: "Cox's Bazar: Pristine Sandy Beaches",
    titleBn: "কক্সবাজার: অবিচ্ছিন্ন বালুকাময় সমুদ্র সৈকত",
    price: 5900,
    duration: "3 Days, 2 Nights",
    durationBn: "৩ দিন, ২ রাত",
    description: "Relax on the world's longest natural sandy beach. Take a walk along the marine drive, explore Himchari, and enjoy fresh seafood.",
    descriptionBn: "বিশ্বের দীর্ঘতম প্রাকৃতিক বালুকাময় সমুদ্র সৈকতে অবসর সময় কাটান। মেরিন ড্রাইভ ধরে ঘুরে বেড়ান, হিমছড়ি দেখুন এবং তাজা সি-ফুড উপভোগ করুন।",
    location: "Cox's Bazar",
    locationBn: "কক্সবাজার",
    distanceNote: "390 km from Dhaka",
    imgUrl: "/images/coxsbazar.png",
    popular: true,
    startDate: "2026-06-20",
    endDate: "2026-06-23",
    rating: "9.3",
    reviews: "210",
    inclusions: [
      "Premium Beachfront Hotel accommodation",
      "Daily complimentary Breakfast",
      "Marine Drive tour in open-hood Jeep",
      "Entry fees to Himchari National Park"
    ],
    itinerary: [
      {
        day: 1,
        title: "Beach Walk and Sunset",
        titleBn: "সৈকত ভ্রমণ ও সূর্যাস্ত",
        description: "Arrive in Cox's Bazar, check in. Spend the afternoon relaxing on the main beach and witnessing the sunset.",
        descriptionBn: "কক্সবাজারে আগমন ও চেক-ইন। বিকেলে মূল সৈকতে ঘুরে বেড়ানো ও সূর্যাস্ত অবলোকন।"
      },
      {
        day: 2,
        title: "Himchari & Inani Beach via Marine Drive",
        titleBn: "মেরিন ড্রাইভ দিয়ে হিমছড়ি ও ইনানী সৈকত",
        description: "Take an exciting ride on the Marine Drive to visit the Himchari Waterfall and the coral-rich Inani Beach.",
        descriptionBn: "মেরিন ড্রাইভ দিয়ে হিমছড়ি ঝর্ণা এবং কোরাল বেষ্টিত ইনানী সৈকতে রোমাঞ্চকর ভ্রমণ।"
      },
      {
        day: 3,
        title: "Souvenir Shopping & Departure",
        titleBn: "স্মারক কেনাকাটা ও প্রস্থান",
        description: "Visit the local Burmese Market for unique souvenirs before boarding your bus back to Dhaka.",
        descriptionBn: "ঢাকার উদ্দেশ্যে বাসে চড়ার আগে স্থানীয় বার্মিজ মার্কেটে স্মারক ও ঐতিহ্যবাহী পণ্য কেনাকাটা।"
      }
    ],
    reviewsBreakdown: {
      "Location": 9.6,
      "Cleanliness": 9.1,
      "Service": 9.3,
      "Value for Money": 9.2
    }
  },
  {
    title: "Sylhet: Tea Gardens & Swamp Forests",
    titleBn: "সিলেট: চা বাগান ও জলাবন অভিযান",
    price: 4800,
    duration: "2 Days, 1 Night",
    durationBn: "২ দিন, ১ রাত",
    description: "Explore the green carpet-like tea gardens of Sreemangal, boat through Ratargul Swamp Forest, and experience the crystal-clear waters of Jaflong.",
    descriptionBn: "শ্রীমঙ্গলের সবুজ গালিচার মতো চা বাগান ঘুরে দেখুন, রাতারগুল জলাবনে নৌকা ভ্রমণ করুন এবং জাফলংয়ের স্ফটিক স্বচ্ছ পানি উপভোগ করুন।",
    location: "Sylhet",
    locationBn: "সিলেট",
    distanceNote: "240 km from Dhaka",
    imgUrl: "/images/sylhet.png",
    popular: false,
    startDate: "2026-06-27",
    endDate: "2026-06-29",
    rating: "9.4",
    reviews: "89",
    inclusions: [
      "Hotel accommodation in Sylhet town",
      "Traditional Sylheti Lunch with Shatkora beef/fish",
      "Private boat hire at Ratargul Swamp Forest",
      "Local transport for sightseeing"
    ],
    itinerary: [
      {
        day: 1,
        title: "Ratargul Swamp Forest Boat Ride",
        titleBn: "রাতারগুল জলাবনে নৌকা ভ্রমণ",
        description: "Explore the only freshwater swamp forest in Bangladesh by a country boat. Watch the beautiful submerged trees.",
        descriptionBn: "দেশীয় নৌকায় করে বাংলাদেশের একমাত্র মিঠাপানির জলাবন ঘুরে দেখুন। পানিতে নিমজ্জিত সুন্দর গাছপালা অবলোকন।"
      },
      {
        day: 2,
        title: "Jaflong Crystal Clear Water & Tea Gardens",
        titleBn: "জাফলংয়ের স্বচ্ছ পানি ও চা বাগান",
        description: "Visit the scenic Jaflong bordering India, explore the tea estates, and witness the stone collection process.",
        descriptionBn: "ভারতের সীমান্তবর্তী মনোরম জাফলং ভ্রমণ, চা বাগান পরিদর্শন এবং পাথর সংগ্রহের অনন্য দৃশ্য উপভোগ।"
      }
    ],
    reviewsBreakdown: {
      "Location": 9.5,
      "Cleanliness": 9.2,
      "Service": 9.4,
      "Value for Money": 9.5
    }
  },
  {
    title: "Sundarbans: Deep Forest Cruise",
    titleBn: "সুন্দরবন: গভীর জঙ্গল ক্রুজ",
    price: 15500,
    duration: "4 Days, 3 Nights",
    durationBn: "৪ দিন, ৩ রাত",
    description: "Journey deep into the world's largest mangrove forest. Watch wildlife, including Royal Bengal Tigers and spotted deer.",
    descriptionBn: "বিশ্বের বৃহত্তম ম্যানগ্রোভ বনের গভীরে যাত্রা। রয়্যাল বেঙ্গল টাইগার এবং চিত্রা হরিণসহ বন্যপ্রাণী প্রত্যক্ষ করুন।",
    location: "Sundarbans",
    locationBn: "সুন্দরবন",
    distanceNote: "280 km from Dhaka",
    imgUrl: "/images/sylhet.png",
    popular: true,
    startDate: "2026-07-02",
    endDate: "2026-07-06",
    rating: "9.7",
    reviews: "155",
    inclusions: ["Cabin accommodation", "Expert naturalist guide", "Forest permit"],
    itinerary: [
      { day: 1, title: "Harbaria Trail Walk", titleBn: "হাড়বাড়িয়া ট্রেইল ওয়াক", description: "Walk through wooden bridges and look for tiger pugmarks.", descriptionBn: "কাঠের ব্রিজ দিয়ে জঙ্গল হাঁটা ও বাঘের পায়ের ছাপ খোঁজা।" }
    ],
    reviewsBreakdown: { "Location": 9.9, "Cleanliness": 9.4, "Service": 9.8, "Value for Money": 9.6 }
  },
  {
    title: "Saint Martin: Coral Island Escape",
    titleBn: "সেন্ট মার্টিন: কোরাল দ্বীপ ভ্রমণ",
    price: 8900,
    duration: "3 Days, 2 Nights",
    durationBn: "৩ দিন, ২ রাত",
    description: "Enjoy the turquoise water, palm-fringed sands, and coral reefs of Bangladesh's only coral island.",
    descriptionBn: "বাংলাদেশের একমাত্র প্রবাল দ্বীপ সেন্ট মার্টিনের নীল জলরাশি ও নারিকেল গাছ ঘেরা সৈকত উপভোগ করুন।",
    location: "Saint Martin",
    locationBn: "সেন্ট মার্টিন",
    distanceNote: "480 km from Dhaka",
    imgUrl: "/images/coxsbazar.png",
    popular: true,
    startDate: "2026-07-10",
    endDate: "2026-07-13",
    rating: "9.5",
    reviews: "120",
    inclusions: ["Ship ticket", "Resort stay", "Complimentary green coconut"],
    itinerary: [
      { day: 1, title: "Chera Dwip Boat Tour", titleBn: "ছেঁড়াদ্বীপ নৌকা ভ্রমণ", description: "Take a speed boat to Chera Dwip to explore the pristine coral reef.", descriptionBn: "স্পিডবোটে করে ছেঁড়াদ্বীপ ভ্রমণ ও আসল কোরাল রিফ দেখা।" }
    ],
    reviewsBreakdown: { "Location": 9.8, "Cleanliness": 9.0, "Service": 9.2, "Value for Money": 9.4 }
  },
  {
    title: "Bandarban: Heights of Nilgiri",
    titleBn: "বান্দরবান: নীলগিরির উচ্চতা",
    price: 7200,
    duration: "3 Days, 2 Nights",
    durationBn: "৩ দিন, ২ রাত",
    description: "Stand atop the clouds at Nilgiri and Nilachal. Visit tribal villages and see the scenic Sangu river.",
    descriptionBn: "নীলগিরি এবং নীলাচলের চূড়ায় দাঁড়িয়ে মেঘ স্পর্শ করুন। পাহাড়ি উপজাতি গ্রাম এবং মনোরম সাঙ্গু নদী ঘুরে দেখুন।",
    location: "Bandarban",
    locationBn: "বান্দরবান",
    distanceNote: "360 km from Dhaka",
    imgUrl: "/images/sajek.png",
    popular: false,
    startDate: "2026-07-15",
    endDate: "2026-07-18",
    rating: "9.4",
    reviews: "95",
    inclusions: ["Hill resort stay", "Local transport", "Guided tribal village tour"],
    itinerary: [
      { day: 1, title: "Sangu River Boat Cruise", titleBn: "সাঙ্গু নদীতে নৌকা ভ্রমণ", description: "Take a scenic traditional boat ride on the crystal clear Sangu River.", descriptionBn: "স্বচ্ছ সাঙ্গু নদীতে ঐতিহ্যবাহী নৌकाय চড়ে পাহাড়ি সৌন্দর্য উপভোগ।" }
    ],
    reviewsBreakdown: { "Location": 9.7, "Cleanliness": 9.2, "Service": 9.5, "Value for Money": 9.3 }
  },
  {
    title: "Kuakata: Sunrise & Sunset Majesty",
    titleBn: "কুয়াকাটা: সূর্যোদয় ও সূর্যাস্তের লীলাभूमि",
    price: 6800,
    duration: "3 Days, 2 Nights",
    durationBn: "৩ দিন, ২ রাত",
    description: "Witness both sunrise and sunset from the same sandy beach of Kuakata. Visit mangrove parks and Red Crab Island.",
    descriptionBn: "কুয়াকাটার একই সৈকত থেকে সূর্যোদয় এবং সূর্যাস্ত উভয়ই প্রত্যক্ষ করুন। লাল কাঁকড়ার দ্বীপ ভ্রমণ করুন।",
    location: "Kuakata, Patuakhali",
    locationBn: "কুয়াকাটা, পটুয়াখালী",
    distanceNote: "290 km from Dhaka",
    imgUrl: "/images/coxsbazar.png",
    popular: false,
    startDate: "2026-07-22",
    endDate: "2026-07-25",
    rating: "9.2",
    reviews: "78",
    inclusions: ["Hotel stay", "Seafood dinner", "Guided bike ride on the beach"],
    itinerary: [
      { day: 1, title: "Sunrise at Gangamati Forest", titleBn: "গঙ্গামতি বনে সূর্যোদয়", description: "Watch the spectacular sunrise over the sea at Gangamati forest.", descriptionBn: "গঙ্গামতি বনের মোহনায় সাগরের বুক চিরে সূর্যোদয়ের অপরূপ দৃশ্য দেখা।" }
    ],
    reviewsBreakdown: { "Location": 9.4, "Cleanliness": 9.0, "Service": 9.1, "Value for Money": 9.3 }
  },
  {
    title: "Tanguar Haor: Luxury Houseboat Expedition",
    titleBn: "টাঙ্গুয়ার হাওর: বিলাসবহুল হাউসবোট অভিযান",
    price: 9500,
    duration: "2 Days, 2 Nights",
    durationBn: "২ দিন, ২ রাত",
    description: "Sail across the vast wetlands of Tanguar Haor on a premium wooden houseboat. Swim in clear water and watch the stars.",
    descriptionBn: "একটি প্রিমিয়াম কাঠের হাউসবোটে চড়ে টাঙ্গুয়ার হাওরের বিশাল জলাভূমি ঘুরে দেখুন। নীল জলে সাঁতার কাটুন ও তারা দেখুন।",
    location: "Sunamganj, Sylhet",
    locationBn: "সুনামগঞ্জ, সিলেট",
    distanceNote: "290 km from Dhaka",
    imgUrl: "/images/sylhet.png",
    popular: true,
    startDate: "2026-08-01",
    endDate: "2026-08-03",
    rating: "9.8",
    reviews: "185",
    inclusions: ["Full board meals on boat", "Premium wooden cabin", "Kayaking & lifejackets"],
    itinerary: [
      { day: 1, title: "Watchtower Swim & Sunset", titleBn: "ওয়াচটাওয়ারে সাঁতার ও সূর্যাস্ত", description: "Swim in crystal-clear water near the forest watchtower.", descriptionBn: "হাওরের ওয়াচটাওয়ারের পাশে স্ফটিকের মতো স্বচ্ছ জলে সাঁতার ও সূর্যাস্ত।" }
    ],
    reviewsBreakdown: { "Location": 9.9, "Cleanliness": 9.6, "Service": 9.8, "Value for Money": 9.7 }
  },
  {
    title: "Sreemangal: Rainforest & Wildlife Walk",
    titleBn: "শ্রীমঙ্গল: রেইনফরেস্ট ও বন্যপ্রাণী হাঁটা",
    price: 4500,
    duration: "2 Days, 1 Night",
    durationBn: "২ দিন, ১ রাত",
    description: "Trek through Lawachara Rainforest, home to rare gibbons. Taste the famous 7-layer tea at Nilkantha Cabin.",
    descriptionBn: "বিরল গিবন বানরের বাসস্থান লাউয়াছড়া রেইনফরেস্টে ট্র্যাকিং। নীলকণ্ঠ কেবিনে বিখ্যাত ৭ রঙের চা উপভোগ করুন।",
    location: "Sreemangal, Moulvibazar",
    locationBn: "শ্রীমঙ্গল, মৌলভীবাজার",
    distanceNote: "190 km from Dhaka",
    imgUrl: "/images/sylhet.png",
    popular: false,
    startDate: "2026-08-06",
    endDate: "2026-08-08",
    rating: "9.3",
    reviews: "64",
    inclusions: ["Eco-lodge stay", "Guided trek in Lawachara", "Complimentary 7-layer tea"],
    itinerary: [
      { day: 1, title: "Spotting Hoolock Gibbons", titleBn: "উল্লুক পর্যবেক্ষণ", description: "Search for the endangered Hoolock Gibbons early in the morning.", descriptionBn: "ভোরবেলা লাউয়াছড়ার গহীন বনে বিলুপ্তপ্রায় উল্লুকের সন্ধান করা।" }
    ],
    reviewsBreakdown: { "Location": 9.5, "Cleanliness": 9.1, "Service": 9.2, "Value for Money": 9.4 }
  },
  {
    title: "Sonargaon: Historic Golden Capital Heritage",
    titleBn: "সোনারগাঁও: প্রাচীন গৌরবময় রাজধানী ঐতিহ্য",
    price: 2500,
    duration: "1 Day",
    durationBn: "১ দিন",
    description: "Explore Panam Nagar, the ruined city of wealthy Hindu merchants. Visit the Folk Art and Craft Museum.",
    descriptionBn: "ধনী বণিকদের পরিত্যক্ত রূপসী শহর পানাম নগরী ঘুরে দেখুন। লোকশিল্প ও কারুশিল্প জাদুঘর পরিদর্শন করুন।",
    location: "Sonargaon, Narayanganj",
    locationBn: "সোনারগাঁও, নারায়ণগঞ্জ",
    distanceNote: "35 km from Dhaka",
    imgUrl: "/images/sajek.png",
    popular: false,
    startDate: "2026-08-10",
    endDate: "2026-08-10",
    rating: "9.0",
    reviews: "52",
    inclusions: ["AC transport from Dhaka", "Museum entry tickets", "Traditional local lunch"],
    itinerary: [
      { day: 1, title: "Panam Nagar Historical Walk", titleBn: "পানাম নগরে ঐতিহাসিক হাঁটা", description: "Walk down the main street of Panam Nagar to see the 19th-century architecture.", descriptionBn: "উনিশ শতকের চমৎকার টেরাকোটা ও স্থাপত্যশৈলীতে নির্মিত পানাম নগরে ঐতিহাসিক পদচারণা।" }
    ],
    reviewsBreakdown: { "Location": 9.2, "Cleanliness": 8.8, "Service": 9.0, "Value for Money": 9.1 }
  },
  {
    title: "Kaptai Lake: Island Resort Escape",
    titleBn: "কাপ্তাই হ্রদ: দ্বীপ রিসোর্ট ভ্রমণ",
    price: 7800,
    duration: "3 Days, 2 Nights",
    durationBn: "৩ দিন, ২ রাত",
    description: "Cruise across the largest man-made lake in Bangladesh. Stay at a beautiful island resort and enjoy kayaking.",
    descriptionBn: "বাংলাদেশের বৃহত্তম কৃত্রিম হ্রদে নৌভ্রমণ। সুন্দর দ্বীপের মনোরম রিসোর্টে থাকুন এবং কায়াকিং করুন।",
    location: "Kaptai, Rangamati",
    locationBn: "কাপ্তাই, রাঙ্গামাটি",
    distanceNote: "320 km from Dhaka",
    imgUrl: "/images/sajek.png",
    popular: false,
    startDate: "2026-08-15",
    endDate: "2026-08-18",
    rating: "9.5",
    reviews: "82",
    inclusions: ["Lakeside cottage stay", "Boat ride to Shuvolong Waterfall", "Kayaking gear"],
    itinerary: [
      { day: 1, title: "Shuvolong Waterfall boat trip", titleBn: "শুভলং ঝর্ণা নৌকা ভ্রমণ", description: "Enjoy a scenic boat cruise on Kaptai lake to visit Shuvolong Waterfall.", descriptionBn: "কাপ্তাই হ্রদে নৌভ্রমণের মাধ্যমে দৃষ্টিনন্দন শুভলং ঝর্ণা পরিদর্শন।" }
    ],
    reviewsBreakdown: { "Location": 9.7, "Cleanliness": 9.3, "Service": 9.5, "Value for Money": 9.4 }
  },
  {
    title: "Bagerhat: Ancient Mosque Heritage",
    titleBn: "বাগেরহাট: ষাট গম্বুজ মসজিদ ও ঐতিহ্য",
    price: 4900,
    duration: "2 Days, 1 Night",
    durationBn: "২ দিন, ১ রাত",
    description: "Discover the UNESCO World Heritage Sixty Dome Mosque. Visit the shrine of Khan Jahan Ali and historic sights.",
    descriptionBn: "ইউনেস্কো বিশ্ব ঐতিহ্য ষাট গম্বুজ মসজিদ আবিষ্কার করুন। হযরত খান জাহান আলীর মাজার ও দীঘি পরিদর্শন করুন।",
    location: "Bagerhat, Khulna",
    locationBn: "বাগেরহাট, খুলনা",
    distanceNote: "220 km from Dhaka",
    imgUrl: "/images/sylhet.png",
    popular: false,
    startDate: "2026-08-20",
    endDate: "2026-08-22",
    rating: "9.1",
    reviews: "45",
    inclusions: ["AC Hotel room", "Local guide support", "Museum entry"],
    itinerary: [
      { day: 1, title: "Sixty Dome Mosque tour", titleBn: "ষাট গম্বুজ মসজিদ পরিভ্রমণ", description: "Explore the medieval Islamic architecture of the famous Sixty Dome Mosque.", descriptionBn: "মধ্যযুগীয় ইসলামী স্থাপত্যের অনন্য নিদর্শন ঐতিহাসিক ষাট গম্বুজ মসজিদ ও জাদুঘর পরিদর্শন।" }
    ],
    reviewsBreakdown: { "Location": 9.3, "Cleanliness": 9.0, "Service": 9.1, "Value for Money": 9.2 }
  },
  {
    title: "Lalakhal: Emerald River Boat Ride",
    titleBn: "লালাখাল: নীল জলের নদী ভ্রমণ",
    price: 3500,
    duration: "1 Day",
    durationBn: "১ দিন",
    description: "Cruise on the emerald blue waters of Lalakhal River. Enjoy the green hills of Jaintiapur bordering India.",
    descriptionBn: "লালাখালের পান্না-সবুজ জলরাশিতে নৌভ্রমণ। ভারতের সীমান্তবর্তী জৈন্তাপুরের অপরূপ সবুজ পাহাড় দেখুন।",
    location: "Lalakhal, Sylhet",
    locationBn: "লালাখাল, সিলেট",
    distanceNote: "270 km from Dhaka",
    imgUrl: "/images/sylhet.png",
    popular: false,
    startDate: "2026-08-25",
    endDate: "2026-08-25",
    rating: "9.3",
    reviews: "60",
    inclusions: ["Boat cruise fee", "Traditional lunch", "Hotel pick & drop in Sylhet"],
    itinerary: [
      { day: 1, title: "Sari River Cruise", titleBn: "শাড়ী নদী ক্রুজ", description: "Float on the clear green waters of Sari River towards the zero point.", descriptionBn: "শাড়ী নদীর স্বচ্ছ ও সবুজাভ জলের ওপর দিয়ে ভারত সীমান্তের জিরো পয়েন্টের দিকে যাত্রা।" }
    ],
    reviewsBreakdown: { "Location": 9.6, "Cleanliness": 9.1, "Service": 9.2, "Value for Money": 9.4 }
  },
  {
    title: "Nijhum Dwip: Deer Sanctuary Island",
    titleBn: "নিঝুম দ্বীপ: হরিণ অভয়ারণ্য দ্বীপ",
    price: 11200,
    duration: "4 Days, 3 Nights",
    durationBn: "৪ দিন, ৩ রাত",
    description: "Travel to the remote southern island of Nijhum Dwip. Spot herds of wild spotted deer and enjoy pristine beaches.",
    descriptionBn: "নোয়াখালীর বিচ্ছিন্ন নিঝুম দ্বীপে যাত্রা। শত শত চিত্রা হরিণের পাল প্রত্যক্ষ করুন ও সম্পূর্ণ কোলাহলমুক্ত সৈকত উপভোগ করুন।",
    location: "Nijhum Dwip, Noakhali",
    locationBn: "নিঝুম দ্বীপ, নোয়াখালী",
    distanceNote: "310 km from Dhaka",
    imgUrl: "/images/coxsbazar.png",
    popular: false,
    startDate: "2026-09-02",
    endDate: "2026-09-06",
    rating: "9.4",
    reviews: "54",
    inclusions: ["Hotel stay on island", "Forest guard security", "Traditional local boat hire"],
    itinerary: [
      { day: 1, title: "Deer Spotting Walk", titleBn: "হরিণ খোঁজার হাঁটা পথ", description: "Walk silently in the mangrove channels to watch deer drinking water.", descriptionBn: "জলাবনের খালের মধ্য দিয়ে হেঁটে নীরবে চিত্রা হরিণের জলপানের দৃশ্য দেখা।" }
    ],
    reviewsBreakdown: { "Location": 9.6, "Cleanliness": 8.8, "Service": 9.2, "Value for Money": 9.4 }
  },
  {
    title: "Birishiri: Ceramic Lake Exploration",
    titleBn: "বিরিশিরি: চীনা মাটির হ্রদ অভিযান",
    price: 5200,
    duration: "2 Days, 1 Night",
    durationBn: "২ দিন, ১ রাত",
    description: "Admire the turquoise blue waters of the Chinese Clay Lake. Cross the scenic Shomeshwari River.",
    descriptionBn: "চীনা মাটির পাহাড়ের পাদদেশে অবস্থিত নীল পানির হ্রদ ঘুরে দেখুন। মনোরম সোমেশ্বরী নদী পার হোন।",
    location: "Birishiri, Netrokona",
    locationBn: "বিরিশিরি, নেত্রকোনা",
    distanceNote: "180 km from Dhaka",
    imgUrl: "/images/sajek.png",
    popular: false,
    startDate: "2026-09-10",
    endDate: "2026-09-12",
    rating: "9.1",
    reviews: "48",
    inclusions: ["Guest house stay", "Local transport (Rickshaw/Auto)", "Guided ceramic lake tour"],
    itinerary: [
      { day: 1, title: "Climbing Ceramic Hills", titleBn: "চীনা মাটির পাহাড়ে আরোহণ", description: "Hike up the white clay hills for a panoramic view of the turquoise lake.", descriptionBn: "সাদা মাটির পাহাড়ের চূড়ায় উঠে হ্রদের শান্ত ও চমৎকার নীল পানি অবলোকন।" }
    ],
    reviewsBreakdown: { "Location": 9.3, "Cleanliness": 8.9, "Service": 9.0, "Value for Money": 9.2 }
  },
  {
    title: "Paharpur: Buddhist Vihara Antiquity",
    titleBn: "পাহাড়পুর: বৌদ্ধ বিহার পুরাকীর্তি",
    price: 5500,
    duration: "2 Days, 1 Night",
    durationBn: "২ দিন, ১ রাত",
    description: "Step back in time at Somapura Mahavihara, the largest ancient Buddhist monastery in the subcontinent.",
    descriptionBn: "উপমহাদেশের বৃহত্তম প্রাচীন বৌদ্ধ বিহার সোমপুর মহাবিহার বা পাহাড়পুর বিহার ঘুরে দেখুন।",
    location: "Paharpur, Naogaon",
    locationBn: "পাহাড়পুর, নওগাঁ",
    distanceNote: "270 km from Dhaka",
    imgUrl: "/images/sajek.png",
    popular: false,
    startDate: "2026-09-15",
    endDate: "2026-09-17",
    rating: "9.2",
    reviews: "38",
    inclusions: ["AC Hotel room in Naogaon", "Museum tickets", "Heritage tour guide"],
    itinerary: [
      { day: 1, title: "Exploring the Central Temple", titleBn: "কেন্দ্রীয় মন্দির পরিভ্রমণ", description: "Inspect the ancient terracotta plaques lining the base of the massive temple.", descriptionBn: "পাহাড়পুর মন্দিরের চারপাশের দেয়ালে খোদাই করা চমৎকার পোড়ামাটির ফলকগুলো দেখা।" }
    ],
    reviewsBreakdown: { "Location": 9.4, "Cleanliness": 9.0, "Service": 9.1, "Value for Money": 9.3 }
  },
  {
    title: "Rangamati: Hill Tracts & Tribal Life",
    titleBn: "রাঙ্গামাটি: পার্বত্য অঞ্চল ও উপজাতীয় জীবন",
    price: 6300,
    duration: "3 Days, 2 Nights",
    durationBn: "৩ দিন, ২ রাত",
    description: "Cross the famous Hanging Bridge, buy local textiles at tribal markets, and visit hillside waterfalls.",
    descriptionBn: "বিখ্যাত ঝুলন্ত ব্রিজ পার হোন, উপজাতীয় বাজারে কেনাকাটা করুন এবং পাহাড়ি ঝর্ণা উপভোগ করুন।",
    location: "Rangamati",
    locationBn: "রাঙ্গামাটি",
    distanceNote: "310 km from Dhaka",
    imgUrl: "/images/sajek.png",
    popular: false,
    startDate: "2026-09-20",
    endDate: "2026-09-23",
    rating: "9.3",
    reviews: "67",
    inclusions: ["Lakeside cottage stay", "Hanging Bridge entry fee", "Tribal food dinner"],
    itinerary: [
      { day: 1, title: "Hanging Bridge & Rajbari Visit", titleBn: "ঝুলন্ত ব্রিজ ও রাজবাড়ি পরিদর্শন", description: "Walk on the suspension bridge and visit the Rangamati Chakma Rajbari.", descriptionBn: "ঝুলন্ত ব্রিজে হাঁটা এবং রাঙ্গামাটির চাকমা রাজবাড়ি ঘুরে ঐতিহাসিক তথ্য জানা।" }
    ],
    reviewsBreakdown: { "Location": 9.5, "Cleanliness": 9.1, "Service": 9.3, "Value for Money": 9.3 }
  },
  {
    title: "Keokradong: Peak Trekking Adventure",
    titleBn: "কেওক্রাডং: পর্বত শৃঙ্গ ট্র্যাকিং",
    price: 8500,
    duration: "4 Days, 3 Nights",
    durationBn: "৪ দিন, ৩ রাত",
    description: "Trek to the summit of Keokradong, one of the highest peaks in Bangladesh. Stay at Boga Lake in a hillside cottage.",
    descriptionBn: "বাংলাদেশের অন্যতম সর্বোচ্চ পর্বত শৃঙ্গ কেওক্রাডং জয় করুন। বগা লেকের পাহাড়ি কুটিরে থাকার রোমাঞ্চকর অভিজ্ঞতা নিন।",
    location: "Bandarban",
    locationBn: "বান্দরবান",
    distanceNote: "390 km from Dhaka",
    imgUrl: "/images/sajek.png",
    popular: true,
    startDate: "2026-09-25",
    endDate: "2026-09-29",
    rating: "9.6",
    reviews: "112",
    inclusions: ["Boga lake cottage stay", "Trekking guide", "All meals in remote hills"],
    itinerary: [
      { day: 1, title: "Hike from Boga Lake to Keokradong", titleBn: "বগা লেক থেকে কেওক্রাডং ট্র্যাকিং", description: "Trek up through winding mountain paths and tribal settlements.", descriptionBn: "বগা লেক থেকে পাহাড়ি আঁকাবাঁকা পথ ও উপজাতি পাড়া পেরিয়ে পর্বত শৃঙ্গে আরোহণ।" }
    ],
    reviewsBreakdown: { "Location": 9.8, "Cleanliness": 8.9, "Service": 9.4, "Value for Money": 9.6 }
  },
  {
    title: "Old Dhaka: Heritage Food Walk",
    titleBn: "পুরান ঢাকা: ঐতিহ্যবাহী খাবার ভ্রমণ",
    price: 1800,
    duration: "1 Day",
    durationBn: "১ দিন",
    description: "Savor legendary Old Dhaka biryani, seekh kebabs, and lassi. Visit Lalbagh Fort and Ahsan Manzil.",
    descriptionBn: "পুরান ঢাকার কিংবদন্তি বিরিয়ানি, শিক কাবাব ও লাচ্ছি উপভোগ করুন। লালবাগ কেল্লা এবং আহসান মঞ্জিল ঘুরে দেখুন।",
    location: "Old Dhaka, Dhaka",
    locationBn: "পুরান ঢাকা, ঢাকা",
    distanceNote: "0 km from Dhaka",
    imgUrl: "/images/sajek.png",
    popular: false,
    startDate: "2026-10-02",
    endDate: "2026-10-02",
    rating: "9.2",
    reviews: "135",
    inclusions: ["All food tastings", "Historic monument entry tickets", "Expert local storyteller"],
    itinerary: [
      { day: 1, title: "Lalbagh Fort & Biryani Dinner", titleBn: "লালবাগ কেল্লা ও বিরিয়ানি ভোজ", description: "Explore the Mughal-era fort before visiting a historic eatery.", descriptionBn: "মুঘল আমলের ঐতিহাসিক দুর্গ লালবাগ কেল্লা পরিদর্শনের পর বিখ্যাত কচি বিরিয়ানি ভোজ।" }
    ],
    reviewsBreakdown: { "Location": 9.3, "Cleanliness": 8.5, "Service": 9.2, "Value for Money": 9.5 }
  },
  {
    title: "Bishanakandi: Rocky Mountain Stream",
    titleBn: "বিছনাকান্দি: পাহাড়ি পাথুরে নদী",
    price: 3900,
    duration: "1 Day",
    durationBn: "১ দিন",
    description: "Bathe in the crystal-clear water flowing down Indian hills. See the layers of rocks in the river bed.",
    descriptionBn: "ভারতের মেঘালয় পাহাড় থেকে নেমে আসা স্বচ্ছ শীতল পানিতে গোসল করুন ও নদীর পাথুরে তলদেশ উপভোগ করুন।",
    location: "Sylhet",
    locationBn: "সিলেট",
    distanceNote: "280 km from Dhaka",
    imgUrl: "/images/sylhet.png",
    popular: false,
    startDate: "2026-10-05",
    endDate: "2026-10-05",
    rating: "9.4",
    reviews: "56",
    inclusions: ["Boat ride from Hadarpar", "Traditional lunch", "Private transport from Sylhet town"],
    itinerary: [
      { day: 1, title: "Hadarpar Boat Journey", titleBn: "হাদারপার নৌকা যাত্রা", description: "Take a scenic local engine boat from Hadarpar bazaar to Bishanakandi.", descriptionBn: "হাদারপার বাজার থেকে বিছনাকান্দির দিকে নদীপথে দৃষ্টিনন্দন ইঞ্জিনের নৌকা ভ্রমণ।" }
    ],
    reviewsBreakdown: { "Location": 9.7, "Cleanliness": 9.0, "Service": 9.2, "Value for Money": 9.5 }
  },
  {
    title: "Ratargul: Kayaking Swamp Forest",
    titleBn: "রাতারগুল: জলাবনে কায়াকিং অভিযান",
    price: 4200,
    duration: "1 Day",
    durationBn: "১ দিন",
    description: "Paddle your way through the submerged forest of Ratargul. Get close to nature with single or double kayaks.",
    descriptionBn: "রাতারগুলের নিমজ্জিত জলাবনে কায়াকিং করুন। খুব কাছ থেকে পানিবন্দি সবুজ গাছের রূপ উপভোগ করুন।",
    location: "Sylhet",
    locationBn: "সিলেট",
    distanceNote: "260 km from Dhaka",
    imgUrl: "/images/sylhet.png",
    popular: false,
    startDate: "2026-10-10",
    endDate: "2026-10-10",
    rating: "9.5",
    reviews: "73",
    inclusions: ["Premium Kayak rental", "Safety lifejacket", "Expert kayaking guide"],
    itinerary: [
      { day: 1, title: "Kayaking through the Trees", titleBn: "গাছের নিচে কায়াকিং", description: "Paddle inside the dense swamp channels where engine boats cannot go.", descriptionBn: "ইঞ্জিনচালিত নৌকা যে গহীন চ্যানেলে যেতে পারে না, সেখানে নিজস্ব কায়াক বেয়ে পরিভ্রমণ।" }
    ],
    reviewsBreakdown: { "Location": 9.8, "Cleanliness": 9.3, "Service": 9.4, "Value for Money": 9.4 }
  },
  {
    title: "Cox's Bazar: Yacht Charter & Sunset",
    titleBn: "কক্সবাজার: বিলাসবহুল ইয়ট ও সূর্যাস্ত",
    price: 18500,
    duration: "1 Day",
    durationBn: "১ দিন",
    description: "Experience the ultimate luxury. Sail into the Bay of Bengal on a private yacht and watch the golden sunset.",
    descriptionBn: "বিলাসবহুল ভ্রমণের অনন্য রূপ। একটি ব্যক্তিগত চার্টার্ড ইয়টে চড়ে বঙ্গোপসাগরের বুক থেকে মোহময় সূর্যাস্ত দেখুন।",
    location: "Cox's Bazar",
    locationBn: "কক্সবাজার",
    distanceNote: "390 km from Dhaka",
    imgUrl: "/images/coxsbazar.png",
    popular: true,
    startDate: "2026-10-15",
    endDate: "2026-10-15",
    rating: "9.9",
    reviews: "42",
    inclusions: ["Private Yacht Charter for 4 hours", "Live Seafood BBQ on deck", "Premium mocktails"],
    itinerary: [
      { day: 1, title: "Cruising the Bay of Bengal", titleBn: "বঙ্গোপসাগরে ইয়ট ক্রুজ", description: "Depart from the jetty, enjoy seafood barbecue, and watch the sun go down.", descriptionBn: "জেটি থেকে যাত্রা শুরু, তাজা সি-ফুড বার্বিকিউ উপভোগ এবং সাগরের বুকে সূর্যাস্ত অবলোকন।" }
    ],
    reviewsBreakdown: { "Location": 9.9, "Cleanliness": 9.9, "Service": 9.9, "Value for Money": 9.5 }
  },
  {
    title: "Saint Martin: Overnight Camping",
    titleBn: "সেন্ট মার্টিন: সৈকতে ক্যাম্পিং ও বার্বিকিউ",
    price: 9200,
    duration: "2 Days, 1 Night",
    durationBn: "২ দিন, ১ রাত",
    description: "Camp under the stars on the beaches of Saint Martin. Enjoy fresh lobster and sea breeze in a cozy tent.",
    descriptionBn: "সেন্ট মার্টিনের কোরাল সৈকতে তাবুতে রাত কাটানোর অনন্য অভিজ্ঞতা। তাজা গলদা চিংড়ি ও সমুদ্রের বাতাস উপভোগ করুন।",
    location: "Saint Martin",
    locationBn: "সেন্ট মার্টিন",
    distanceNote: "480 km from Dhaka",
    imgUrl: "/images/coxsbazar.png",
    popular: false,
    startDate: "2026-10-20",
    endDate: "2026-10-21",
    rating: "9.4",
    reviews: "58",
    inclusions: ["Premium camping tent", "Seafood barbecue dinner", "Ship transit tickets"],
    itinerary: [
      { day: 1, title: "Campfire & Stargazing", titleBn: "ক্যাম্পফায়ার ও তারা দেখা", description: "Set up camp and enjoy a warm campfire with music under a clear starry sky.", descriptionBn: "সৈকতে তাবু স্থাপন ও পরিষ্কার আকাশ تলে গান ও বারবিকিউ সহ ক্যাম্পফায়ার।" }
    ],
    reviewsBreakdown: { "Location": 9.8, "Cleanliness": 9.0, "Service": 9.2, "Value for Money": 9.5 }
  },
  {
    title: "Bandarban: Nafakhum Waterfall Odyssey",
    titleBn: "বান্দরবান: নাফাখুম ঝর্ণা অভিযান",
    price: 9800,
    duration: "4 Days, 3 Nights",
    durationBn: "৪ দিন, ৩ রাত",
    description: "Travel to Remakree and hike to Nafakhum Waterfall, the 'Niagara of Bangladesh'. Take boat rides on Sangu River.",
    descriptionBn: "রেমাকরীতে ভ্রমণ এবং নাফাখুম ঝর্ণায় রোমাঞ্চকর ট্র্যাকিং। পাহাড়ি সাঙ্গু নদীতে নৌকায় করে যাতায়াত করুন।",
    location: "Bandarban",
    locationBn: "বান্দরবান",
    distanceNote: "410 km from Dhaka",
    imgUrl: "/images/sajek.png",
    popular: true,
    startDate: "2026-10-25",
    endDate: "2026-10-29",
    rating: "9.7",
    reviews: "88",
    inclusions: ["Remakree tribal resort stay", "Experienced local guide", "Engine boat transport"],
    itinerary: [
      { day: 1, title: "Boat ride to Remakree", titleBn: "রেমাকরীর উদ্দেশ্যে নৌকা যাত্রা", description: "Cruise through the deep rocky canyon of Sangu River towards Remakree.", descriptionBn: "সাঙ্গু নদীর পাথুরে গিরিখাত পেরিয়ে রেমাকরীর পাহাড়ি উপজাতি পাড়ার উদ্দেশ্যে নৌকা যাত্রা।" }
    ],
    reviewsBreakdown: { "Location": 9.9, "Cleanliness": 9.0, "Service": 9.6, "Value for Money": 9.7 }
  },
  {
    title: "Sajek Valley: Cloud Glamping Escape",
    titleBn: "সাজেক ভ্যালি: মেঘের মাঝে গ্ল্যাম্পিং",
    price: 12500,
    duration: "3 Days, 2 Nights",
    durationBn: "৩ দিন, ২ রাত",
    description: "Experience luxury glamping in Sajek Valley. Wake up to panoramic mountain views and modern conveniences.",
    descriptionBn: "সাজেক ভ্যালিতে বিলাসবহুল ক্যাম্পিং বা গ্ল্যাম্পিংয়ের স্বাদ নিন। পাহাড়ে আধুনিক তাঁবু ও চমৎকার ভিউ উপভোগ করুন।",
    location: "Sajek Valley, Rangamati",
    locationBn: "সাজেক ভ্যালি, রাঙ্গামাটি",
    distanceNote: "340 km from Dhaka",
    imgUrl: "/images/sajek.png",
    popular: true,
    startDate: "2026-11-02",
    endDate: "2026-11-05",
    rating: "9.8",
    reviews: "64",
    inclusions: ["Luxury Glamping Dome stay", "Traditional organic meals", "Private tour vehicle"],
    itinerary: [
      { day: 1, title: "Sajek Ridge sunset walk", titleBn: "সাজেক রিজে সূর্যাস্ত ভ্রমণ", description: "Walk along the scenic ridge road of Sajek during golden hour.", descriptionBn: "সাজেক ভ্যালির প্রধান পাহাড়ি রাস্তায় সূর্যাস্তের মনোরম দৃশ্য অবলোকন।" }
    ],
    reviewsBreakdown: { "Location": 9.9, "Cleanliness": 9.8, "Service": 9.8, "Value for Money": 9.4 }
  },
  {
    title: "Dhaka: Art Galleries & Museums",
    titleBn: "ঢাকা: আর্ট গ্যালারি ও ইতিহাস ভ্রমণ",
    price: 2200,
    duration: "1 Day",
    durationBn: "১ দিন",
    description: "Visit the Liberation War Museum, National Museum, and top modern art galleries. Guided by an art historian.",
    descriptionBn: "মুক্তিযুদ্ধ জাদুঘর, জাতীয় জাদুঘর এবং শীর্ষস্থানীয় আধুনিক শিল্পকলা গ্যালারিগুলো পরিদর্শন করুন।",
    location: "Dhaka",
    locationBn: "ঢাকা",
    distanceNote: "0 km from Dhaka",
    imgUrl: "/images/sajek.png",
    popular: false,
    startDate: "2026-11-10",
    endDate: "2026-11-10",
    rating: "9.0",
    reviews: "35",
    inclusions: ["All museum entry tickets", "AC microbus transport", "Fine dining lunch"],
    itinerary: [
      { day: 1, title: "National Museum Historical Tour", titleBn: "জাতীয় জাদুঘরে ইতিহাস পরিক্রমা", description: "Explore the ancient relics and heritage halls of Bangladesh National Museum.", descriptionBn: "জাতীয় জাদুঘরের ঐতিহ্যবাহী গ্যালারি এবং প্রাচীন পুরাকীর্তি কক্ষগুলো ঘুরে দেখা।" }
    ],
    reviewsBreakdown: { "Location": 9.1, "Cleanliness": 9.2, "Service": 9.1, "Value for Money": 9.0 }
  },
  {
    title: "Sylhet: Hum Hum Waterfall Trek",
    titleBn: "সিলেট: হামহাম ঝর্ণা অ্যাডভেঞ্চার",
    price: 5800,
    duration: "2 Days, 1 Night",
    durationBn: "২ দিন, ১ রাত",
    description: "Trek through the deep tropical forest of Rajkandi to discover the majestic Hum Hum Waterfall.",
    descriptionBn: "রাজকান্দির গহীন ক্রান্তীয় বনের মধ্য দিয়ে দুর্গম পথ পাড়ি দিয়ে চমৎকার হামহাম জলপ্রপাত আবিষ্কার করুন।",
    location: "Sylhet",
    locationBn: "সিলেট",
    distanceNote: "210 km from Dhaka",
    imgUrl: "/images/sylhet.png",
    popular: false,
    startDate: "2026-11-15",
    endDate: "2026-11-17",
    rating: "9.5",
    reviews: "72",
    inclusions: ["Forest bungalow stay", "Local forest guide", "Trekking support gear"],
    itinerary: [
      { day: 1, title: "Trek inside Rajkandi Forest", titleBn: "রাজকান্দি বনে ট্র্যাকিং", description: "Hike up mountain streams and bamboo paths to reach the waterfall.", descriptionBn: "পাহাড়ি ঝিরিপথ ও বাঁশঝাড়ের মধ্য দিয়ে রোমাঞ্চকর ট্র্যাকিং করে জলপ্রপাতে পৌঁছানো।" }
    ],
    reviewsBreakdown: { "Location": 9.8, "Cleanliness": 8.7, "Service": 9.2, "Value for Money": 9.5 }
  }
];
